from __future__ import annotations

"""
NMC-style 500 hPa trough/ridge objective analysis.

This module is designed as a drop-in replacement for the earlier
trough_ridge.py implementation.  It deliberately favours synoptic-scale,
hand-analysis-like smooth axes over noisy grid-scale ridges.

Public API kept compatible:
    detect_trough_ridge(z500, lat, lon, thresholds, vorticity500=None)

Input:
    z500: 2-D geopotential height field [lat, lon].  Values may be gpm/dagpm or
          ECMWF geopotential (m^2 s^-2); if values are very large they are
          converted to gpm automatically.
    lat, lon: 1-D arrays.
    vorticity500: optional 2-D relative vorticity [s^-1], positive supports troughs
                  in the Northern Hemisphere.

Output:
    (trough_features, ridge_features), where each feature is a GeoJSON LineString
    generated by weather_diag.io.geojson.line_feature when available.
"""

from dataclasses import dataclass
from typing import Iterable, Literal

import numpy as np
from scipy import interpolate, ndimage

try:  # keep compatibility with the existing project
    from weather_diag.io.geojson import line_feature
except Exception:  # pragma: no cover - standalone fallback
    def line_feature(coordinates, properties):
        return {
            "type": "Feature",
            "geometry": {"type": "LineString", "coordinates": coordinates},
            "properties": properties,
        }


def _clean_geojson_line_coordinates(coordinates) -> list[list[float]]:
    """Clean coordinates for a GeoJSON LineString axis."""
    arr = np.asarray(coordinates, dtype=float)
    if arr.ndim != 2 or arr.shape[1] < 2:
        return []
    arr = arr[:, :2]
    arr = arr[np.isfinite(arr).all(axis=1)]
    cleaned: list[list[float]] = []
    for lon_value, lat_value in arr:
        point = [float(lon_value), float(lat_value)]
        if cleaned and np.allclose(cleaned[-1], point, atol=1e-10, rtol=0.0):
            continue
        cleaned.append(point)
    # Candidate axes are open lines, never polygon rings.
    if len(cleaned) >= 3 and np.allclose(cleaned[0], cleaned[-1], atol=1e-10, rtol=0.0):
        cleaned = cleaned[:-1]
    return cleaned


def _strict_line_feature(coordinates, properties: dict) -> dict:
    """Return a strict GeoJSON LineString feature with no area-like payload."""
    props = dict(properties)
    # Avoid names often used by generic GIS adapters to create rectangle/polygon
    # overlays.
    for key in ("bbox", "line_bbox", "extent", "polygon", "area", "mask", "component_mask"):
        props.pop(key, None)
    props["geometry_type"] = "LineString"
    return {
        "type": "Feature",
        "geometry": {
            "type": "LineString",
            "coordinates": _clean_geojson_line_coordinates(coordinates),
        },
        "properties": props,
    }

Mode = Literal["trough", "ridge"]
G0 = 9.80665
EARTH_KM_PER_DEG = 111.32


@dataclass(frozen=True)
class NmcStyleConfig:
    # Analysis domain.  500 hPa synoptic troughs in this product should normally
    # be judged in the mid-latitude belt; this also removes many tropical/boundary
    # artefacts like the Sri Lanka/Indian Ocean wiggles in the screenshot.
    analysis_lat_min: float = 18.0
    analysis_lat_max: float = 68.0
    analysis_lon_min: float = -180.0
    analysis_lon_max: float = 360.0

    # Smooth by physical scale, not by raw grid count.  This is important when EC
    # fields are 0.1/0.25 deg: hand-analysis troughs are synoptic-scale systems.
    smooth_radius_km: float = 220.0
    min_sigma_grid: float = 1.2
    second_smooth_radius_km: float = 120.0

    # Candidate score thresholds.  Components are grown from component_percentile
    # but must contain at least one seed above seed_percentile.
    component_percentile: float = 86.0
    seed_percentile: float = 93.0
    local_extreme_min_score: float = 0.20
    curvature_min_score: float = 0.08

    # Component and output filtering.
    min_points_per_line: int = 10
    min_length_km: float = 650.0
    max_lines: int = 6
    edge_margin_grid: int = 2
    reject_tropical_zonal: bool = True
    low_lat_zonal_filter_max_lat: float = 26.0
    low_lat_zonal_max_aspect_ratio: float = 2.5

    # Sparse sounding fields can contain a persistent but weak north-south
    # height valley that falls below the global component percentile.  Keep this
    # recovery path opt-in so the model-grid detector contract is unchanged.
    enable_meridional_valley_tracks: bool = False
    meridional_track_lon_min: float = 75.0
    meridional_track_lon_max: float = 135.0
    meridional_track_lat_min: float = 20.0
    meridional_track_lat_max: float = 55.0
    meridional_track_window_km: float = 280.0
    meridional_track_min_depth_gpm: float = 0.6
    meridional_track_max_gap_rows: int = 2
    meridional_track_max_lon_step_deg: float = 2.2
    meridional_track_min_points: int = 5
    meridional_track_min_lat_span_deg: float = 4.0
    meridional_track_min_mean_depth_gpm: float = 0.8
    meridional_track_min_peak_depth_gpm: float = 1.6
    meridional_track_overlap_distance_km: float = 250.0
    meridional_track_max_existing_coverage: float = 0.5
    meridional_track_max_lines: int = 2

    # Axis construction and drawing style.
    axis_control_spacing_km: float = 260.0
    max_control_points: int = 24
    output_points: int = 28
    spline_smooth_factor: float = 2.8
    principal_curve_iterations: int = 2
    principal_curve_capture_km: float = 420.0
    max_sinuosity: float = 3.0

    # Feature confidence is not a probability.  It is only a visual/business hint.
    base_confidence: float = 0.70


def _cfg_from_thresholds(thresholds: dict | None) -> NmcStyleConfig:
    thresholds = thresholds or {}
    raw = thresholds.get("trough_ridge", thresholds)
    defaults = NmcStyleConfig()
    values = {}
    for field_name in defaults.__dataclass_fields__:  # type: ignore[attr-defined]
        if field_name in raw:
            values[field_name] = raw[field_name]

    # Backward-compatible aliases used by the previous implementation.
    alias = {
        "smoothing_sigma_grid": "min_sigma_grid",
        "min_points": "min_points_per_line",
        "min_points_per_line": "min_points_per_line",
        "max_lines": "max_lines",
    }
    for old_key, new_key in alias.items():
        if old_key in raw and new_key not in values:
            values[new_key] = raw[old_key]

    return NmcStyleConfig(**values)


def _maybe_geopotential_to_height(z: np.ndarray) -> np.ndarray:
    """Convert ECMWF geopotential to geopotential height if needed."""
    arr = np.asarray(z, dtype=float)
    valid = arr[np.isfinite(arr)]
    if valid.size == 0:
        return arr.copy()
    med = float(np.nanmedian(np.abs(valid)))
    # 500 hPa geopotential is around 5.5e4 m2/s2.  Height is around 5500 gpm.
    if med > 20000.0:
        return arr / G0
    return arr.copy()


def _prepare_lat_lon_field(
    field: np.ndarray,
    lat: Iterable[float],
    lon: Iterable[float],
    extra: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray | None]:
    lat_arr = np.asarray(lat, dtype=float)
    lon_arr = np.asarray(lon, dtype=float)
    arr = np.asarray(field, dtype=float)
    ext = None if extra is None else np.asarray(extra, dtype=float)

    if arr.ndim != 2:
        raise ValueError("z500 must be a 2-D array with shape [lat, lon]")
    if arr.shape != (lat_arr.size, lon_arr.size):
        raise ValueError(
            f"z500 shape {arr.shape} does not match lat/lon sizes "
            f"({lat_arr.size}, {lon_arr.size})"
        )
    if ext is not None and ext.shape != arr.shape:
        raise ValueError("vorticity500 shape must match z500")

    if lat_arr.size > 1 and lat_arr[0] > lat_arr[-1]:
        lat_arr = lat_arr[::-1]
        arr = arr[::-1, :]
        if ext is not None:
            ext = ext[::-1, :]
    if lon_arr.size > 1 and lon_arr[0] > lon_arr[-1]:
        lon_arr = lon_arr[::-1]
        arr = arr[:, ::-1]
        if ext is not None:
            ext = ext[:, ::-1]
    return arr, lat_arr, lon_arr, ext


def _lon_km_per_degree(lat: np.ndarray) -> np.ndarray:
    return EARTH_KM_PER_DEG * np.maximum(np.cos(np.deg2rad(lat)), 0.18)


def _grid_spacing_km(lat: np.ndarray, lon: np.ndarray) -> tuple[float, float]:
    dlat = np.nanmedian(np.abs(np.diff(lat))) if lat.size > 1 else 1.0
    dlon = np.nanmedian(np.abs(np.diff(lon))) if lon.size > 1 else 1.0
    mid_lat = float(np.nanmedian(lat)) if lat.size else 35.0
    dy = max(float(dlat) * EARTH_KM_PER_DEG, 1.0)
    dx = max(float(dlon) * EARTH_KM_PER_DEG * max(np.cos(np.deg2rad(mid_lat)), 0.18), 1.0)
    return dy, dx


def _nan_gaussian(field: np.ndarray, sigma_yx: tuple[float, float]) -> np.ndarray:
    arr = np.asarray(field, dtype=float)
    finite = np.isfinite(arr)
    if not finite.any():
        return np.full_like(arr, np.nan, dtype=float)
    filled = np.where(finite, arr, 0.0)
    weights = finite.astype(float)
    smooth = ndimage.gaussian_filter(filled, sigma=sigma_yx, mode="nearest")
    wsum = ndimage.gaussian_filter(weights, sigma=sigma_yx, mode="nearest")
    out = np.full_like(arr, np.nan, dtype=float)
    np.divide(smooth, wsum, out=out, where=wsum > 1e-6)
    return out


def _percentile_score(values: np.ndarray, lower: float = 50.0, upper: float = 92.0) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    valid = arr[np.isfinite(arr)]
    out = np.zeros_like(arr, dtype=float)
    if valid.size == 0:
        return out
    lo = float(np.nanpercentile(valid, lower))
    hi = float(np.nanpercentile(valid, upper))

    # Many diagnostic supports are sparse: most grid points are exactly 0 and
    # only the real axes are positive.  In that case P50/P92 may both be 0,
    # which would erase the signal.  Fall back to positive values only.
    if (not np.isfinite(hi - lo)) or abs(hi - lo) < 1e-12:
        positive = valid[valid > 0.0]
        if positive.size == 0:
            return out
        lo = float(np.nanpercentile(positive, min(lower, 30.0)))
        hi = float(np.nanpercentile(positive, max(upper, 90.0)))
    if not np.isfinite(hi - lo) or abs(hi - lo) < 1e-12:
        hi = float(np.nanmax(valid))
        lo = float(np.nanmin(valid))
    if not np.isfinite(hi - lo) or abs(hi - lo) < 1e-12:
        return out
    out = np.clip((arr - lo) / (hi - lo), 0.0, 1.0)
    return np.where(np.isfinite(out), out, 0.0)


def _finite_percentile(values: np.ndarray, q: float, default: float = 0.0) -> float:
    valid = values[np.isfinite(values)]
    if valid.size == 0:
        return default
    return float(np.nanpercentile(valid, q))


def _metric_derivatives(field: np.ndarray, lat: np.ndarray, lon: np.ndarray) -> tuple[np.ndarray, ...]:
    lon_scale = _lon_km_per_degree(lat)[:, None]
    zy = np.gradient(field, lat, axis=0, edge_order=1) / EARTH_KM_PER_DEG
    zx = np.gradient(field, lon, axis=1, edge_order=1) / lon_scale
    zyy = np.gradient(zy, lat, axis=0, edge_order=1) / EARTH_KM_PER_DEG
    zxx = np.gradient(zx, lon, axis=1, edge_order=1) / lon_scale
    zxy = np.gradient(zx, lat, axis=0, edge_order=1) / EARTH_KM_PER_DEG
    return zx, zy, zxx, zyy, zxy


def _field_features(field: np.ndarray, lat: np.ndarray, lon: np.ndarray) -> dict[str, np.ndarray]:
    zx, zy, zxx, zyy, zxy = _metric_derivatives(field, lat, lon)
    grad_sq = zx * zx + zy * zy
    numerator = zxx * zy * zy - 2.0 * zxy * zx * zy + zyy * zx * zx
    curvature = np.zeros_like(field, dtype=float)
    np.divide(numerator, np.maximum(grad_sq, 1e-12) ** 1.5, out=curvature, where=np.isfinite(numerator))
    return {
        "zx": zx,
        "zy": zy,
        "zxx": zxx,
        "zyy": zyy,
        "zxy": zxy,
        "laplacian": zxx + zyy,
        "contour_curvature": curvature,
        "grad_mag": np.sqrt(np.maximum(grad_sq, 0.0)),
    }


def _shift_with_nan(field: np.ndarray, dy: int, dx: int) -> np.ndarray:
    out = np.full_like(field, np.nan, dtype=float)
    if dy >= 0:
        src_y, dst_y = slice(0, field.shape[0] - dy), slice(dy, field.shape[0])
    else:
        src_y, dst_y = slice(-dy, field.shape[0]), slice(0, field.shape[0] + dy)
    if dx >= 0:
        src_x, dst_x = slice(0, field.shape[1] - dx), slice(dx, field.shape[1])
    else:
        src_x, dst_x = slice(-dx, field.shape[1]), slice(0, field.shape[1] + dx)
    out[dst_y, dst_x] = field[src_y, src_x]
    return out


def _directional_extreme_score(field: np.ndarray, mode: Mode, radius_grid: int = 3) -> np.ndarray:
    """Score whether a point is a local trough/ridge axis in any main direction.

    It uses a multi-grid-radius comparison.  The subsequent synoptic smoothing
    and component filtering make it less noisy than using this score directly.
    """
    score = np.zeros_like(field, dtype=float)
    directions = [(0, 1), (1, 0), (1, 1), (1, -1), (2, 1), (1, 2), (2, -1), (1, -2)]
    for radius in range(1, max(1, int(radius_grid)) + 1):
        for dy, dx in directions:
            plus = _shift_with_nan(field, dy * radius, dx * radius)
            minus = _shift_with_nan(field, -dy * radius, -dx * radius)
            if mode == "trough":
                candidate = np.minimum(plus - field, minus - field)
            else:
                candidate = np.minimum(field - plus, field - minus)
            score = np.nanmax(np.stack([score, np.where(candidate > 0.0, candidate, 0.0)]), axis=0)
    return np.where(np.isfinite(score), score, 0.0)


def _domain_mask(lat: np.ndarray, lon: np.ndarray, cfg: NmcStyleConfig) -> np.ndarray:
    yy = (lat >= cfg.analysis_lat_min) & (lat <= cfg.analysis_lat_max)
    xx = (lon >= cfg.analysis_lon_min) & (lon <= cfg.analysis_lon_max)
    mask = yy[:, None] & xx[None, :]
    m = max(0, int(cfg.edge_margin_grid))
    if m > 0 and mask.shape[0] > 2 * m and mask.shape[1] > 2 * m:
        mask[:m, :] = False
        mask[-m:, :] = False
        mask[:, :m] = False
        mask[:, -m:] = False
    return mask


def _build_score(
    z_smooth: np.ndarray,
    lat: np.ndarray,
    lon: np.ndarray,
    cfg: NmcStyleConfig,
    mode: Mode,
    vorticity: np.ndarray | None,
) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    features = _field_features(z_smooth, lat, lon)
    anom = z_smooth - np.nanmean(z_smooth, axis=1, keepdims=True)

    local_raw = _directional_extreme_score(z_smooth, mode=mode, radius_grid=3)
    local_score = _percentile_score(local_raw, 50, 92)

    lap_support = features["laplacian"] if mode == "trough" else -features["laplacian"]
    lap_score = _percentile_score(np.maximum(lap_support, 0.0), 50, 92)

    # Absolute contour curvature is only a weak visual support.  The trough/ridge
    # sign is mainly controlled by local_score + lap_score + anomaly sign.
    curvature_score = _percentile_score(np.abs(features["contour_curvature"]), 50, 92)

    anom_support = -anom if mode == "trough" else anom
    anom_score = _percentile_score(anom_support, 45, 90)
    grad_score = _percentile_score(features["grad_mag"], 35, 85)

    if vorticity is not None:
        vort_support = vorticity if mode == "trough" else -vorticity
        vort_score = _percentile_score(np.maximum(vort_support, 0.0), 50, 92)
    else:
        vort_score = np.zeros_like(z_smooth, dtype=float)

    score = (
        0.36 * local_score
        + 0.24 * lap_score
        + 0.14 * curvature_score
        + 0.14 * anom_score
        + 0.08 * vort_score
        + 0.04 * grad_score
    )
    score = np.where(np.isfinite(z_smooth), score, 0.0)
    maps = {
        **features,
        "local_score": local_score,
        "lap_score": lap_score,
        "curvature_score": curvature_score,
        "anom_score": anom_score,
        "grad_score": grad_score,
        "vort_score": vort_score,
        "score": score,
        "anom": anom,
    }
    return score, maps


def _candidate_components(
    score: np.ndarray,
    maps: dict[str, np.ndarray],
    valid_mask: np.ndarray,
    cfg: NmcStyleConfig,
) -> list[tuple[np.ndarray, np.ndarray]]:
    domain_values = score[valid_mask & np.isfinite(score)]
    if domain_values.size == 0:
        return []
    component_thr = float(np.nanpercentile(domain_values, cfg.component_percentile))
    seed_thr = float(np.nanpercentile(domain_values, cfg.seed_percentile))

    base = (
        valid_mask
        & (score >= component_thr)
        & (maps["local_score"] >= cfg.local_extreme_min_score)
        & (maps["lap_score"] >= cfg.curvature_min_score)
    )

    # Clean isolated single-pixel noise but do not over-close, which can merge
    # separate troughs into one large area.
    structure = np.ones((3, 3), dtype=bool)
    base = ndimage.binary_opening(base, structure=structure, iterations=1)
    base = ndimage.binary_dilation(base, structure=structure, iterations=1) & valid_mask & (score >= component_thr * 0.92)

    labels, count = ndimage.label(base, structure=structure.astype(int))
    comps: list[tuple[np.ndarray, np.ndarray]] = []
    for label_id in range(1, count + 1):
        ys, xs = np.where(labels == label_id)
        if ys.size < cfg.min_points_per_line:
            continue
        if not np.any(score[ys, xs] >= seed_thr):
            continue
        comps.append((ys, xs))
    return comps


def _lonlat_to_xy_km(lon_values: np.ndarray, lat_values: np.ndarray, lat0: float) -> np.ndarray:
    x = lon_values * EARTH_KM_PER_DEG * max(np.cos(np.deg2rad(lat0)), 0.18)
    y = lat_values * EARTH_KM_PER_DEG
    return np.column_stack([x, y]).astype(float)


def _xy_km_to_lonlat(xy: np.ndarray, lat0: float) -> np.ndarray:
    scale_x = EARTH_KM_PER_DEG * max(np.cos(np.deg2rad(lat0)), 0.18)
    lon = xy[:, 0] / scale_x
    lat = xy[:, 1] / EARTH_KM_PER_DEG
    return np.column_stack([lon, lat]).astype(float)


def _weighted_pca_axis(xy: np.ndarray, weights: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    weights = np.asarray(weights, dtype=float)
    weights = np.where(np.isfinite(weights) & (weights > 0), weights, 0.05)
    center = np.average(xy, axis=0, weights=weights)
    centered = xy - center
    try:
        _, _, vh = np.linalg.svd(centered * np.sqrt(weights[:, None]), full_matrices=False)
        axis = vh[0]
    except np.linalg.LinAlgError:
        axis = np.array([0.0, 1.0])
    norm = float(np.hypot(axis[0], axis[1]))
    if norm <= 1e-9:
        axis = np.array([0.0, 1.0])
    else:
        axis = axis / norm
    return center, axis


def _remove_close_points(xy: np.ndarray, min_step_km: float = 20.0) -> np.ndarray:
    if xy.shape[0] <= 1:
        return xy
    keep = [0]
    for i in range(1, xy.shape[0]):
        if np.hypot(*(xy[i] - xy[keep[-1]])) >= min_step_km:
            keep.append(i)
    return xy[np.asarray(keep, dtype=int)]


def _resample_xy_by_arclength(xy: np.ndarray, count: int) -> np.ndarray:
    if xy.shape[0] == 0:
        return xy
    if xy.shape[0] == 1 or count <= 1:
        return np.repeat(xy[:1], max(1, count), axis=0)
    seg = np.hypot(np.diff(xy[:, 0]), np.diff(xy[:, 1]))
    dist = np.concatenate([[0.0], np.cumsum(seg)])
    total = float(dist[-1])
    if total <= 1e-9:
        return np.repeat(xy[:1], count, axis=0)
    target = np.linspace(0.0, total, count)
    return np.column_stack([
        np.interp(target, dist, xy[:, 0]),
        np.interp(target, dist, xy[:, 1]),
    ])


def _smooth_xy_spline(xy: np.ndarray, count: int, smooth_factor: float) -> np.ndarray:
    xy = _remove_close_points(np.asarray(xy, dtype=float), min_step_km=15.0)
    if xy.shape[0] < 3:
        return _resample_xy_by_arclength(xy, count)

    # Preserve line order and smooth in metric coordinates.  This avoids the
    # grid-snapping saw-tooth that appears when smoothing in lon/lat and then
    # snapping every point to an integer grid cell.
    seg = np.hypot(np.diff(xy[:, 0]), np.diff(xy[:, 1]))
    median_step = float(np.nanmedian(seg)) if seg.size else 1.0
    if not np.isfinite(median_step) or median_step <= 0:
        return _resample_xy_by_arclength(xy, count)
    s_value = float(max(0.0, smooth_factor) * xy.shape[0] * median_step * median_step)
    try:
        spline, _ = interpolate.splprep(
            [xy[:, 0], xy[:, 1]],
            s=s_value,
            k=min(3, xy.shape[0] - 1),
        )
        out = interpolate.splev(np.linspace(0.0, 1.0, count), spline)
        return np.column_stack(out)
    except Exception:
        return _resample_xy_by_arclength(xy, count)


def _initial_axis_from_component(
    ys: np.ndarray,
    xs: np.ndarray,
    lat: np.ndarray,
    lon: np.ndarray,
    score: np.ndarray,
    cfg: NmcStyleConfig,
) -> tuple[np.ndarray, float]:
    lons = lon[xs]
    lats = lat[ys]
    lat0 = float(np.nanmedian(lats))
    xy = _lonlat_to_xy_km(lons, lats, lat0)
    weights = score[ys, xs]
    weights = np.where(np.isfinite(weights) & (weights > 0), weights, 0.05)
    center, axis = _weighted_pca_axis(xy, weights)
    proj = (xy - center) @ axis
    p_min, p_max = float(np.nanmin(proj)), float(np.nanmax(proj))
    if not np.isfinite(p_max - p_min) or p_max <= p_min:
        return xy[:0], lat0

    length_est = p_max - p_min
    bin_count = int(np.ceil(length_est / max(cfg.axis_control_spacing_km, 80.0))) + 1
    bin_count = int(np.clip(bin_count, 5, cfg.max_control_points))
    bins = np.linspace(p_min, p_max, bin_count + 1)

    parts = []
    for i, (left, right) in enumerate(zip(bins[:-1], bins[1:])):
        if i == bin_count - 1:
            mask = (proj >= left) & (proj <= right)
        else:
            mask = (proj >= left) & (proj < right)
        if not np.any(mask):
            continue
        idx = np.where(mask)[0]
        local_w = weights[idx]
        # Use the upper-score half of each slice.  This avoids averaging across
        # a broad component and placing the axis along the area edge.
        if idx.size >= 4:
            cutoff = float(np.nanpercentile(local_w, 55.0))
            good = idx[local_w >= cutoff]
            if good.size:
                idx = good
                local_w = weights[idx]
        parts.append(np.average(xy[idx], axis=0, weights=np.maximum(local_w, 0.05)))

    control = np.asarray(parts, dtype=float)
    if control.shape[0] < 2:
        return xy[:0], lat0
    # Order from west/south to east/north consistently for stable output.
    if abs(control[-1, 1] - control[0, 1]) >= abs(control[-1, 0] - control[0, 0]):
        if control[0, 1] > control[-1, 1]:
            control = control[::-1]
    elif control[0, 0] > control[-1, 0]:
        control = control[::-1]
    return control, lat0


def _principal_curve_refine(
    control: np.ndarray,
    all_xy: np.ndarray,
    weights: np.ndarray,
    cfg: NmcStyleConfig,
) -> np.ndarray:
    if control.shape[0] < 3 or all_xy.shape[0] < 6:
        return control
    curve = _smooth_xy_spline(control, count=max(8, min(cfg.max_control_points, control.shape[0] + 2)), smooth_factor=1.0)
    for _ in range(max(0, int(cfg.principal_curve_iterations))):
        nodes = _resample_xy_by_arclength(curve, max(7, min(cfg.max_control_points, curve.shape[0])))
        # nearest-node assignment is enough here because components are already
        # connected and synoptic-smoothed.
        d2 = ((all_xy[:, None, :] - nodes[None, :, :]) ** 2).sum(axis=2)
        nearest = np.argmin(d2, axis=1)
        new_nodes = []
        capture2 = cfg.principal_curve_capture_km * cfg.principal_curve_capture_km
        for j, node in enumerate(nodes):
            mask = (np.abs(nearest - j) <= 1) & (d2[:, j] <= capture2)
            if np.any(mask):
                w = np.maximum(weights[mask], 0.05)
                new_nodes.append(np.average(all_xy[mask], axis=0, weights=w))
            else:
                new_nodes.append(node)
        curve = _smooth_xy_spline(np.asarray(new_nodes, dtype=float), count=nodes.shape[0], smooth_factor=1.4)
    return curve


def _haversine_length_km(coords: np.ndarray) -> float:
    if coords.shape[0] < 2:
        return 0.0
    lon = np.deg2rad(coords[:, 0])
    lat = np.deg2rad(coords[:, 1])
    dlon = np.diff(lon)
    dlat = np.diff(lat)
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat[:-1]) * np.cos(lat[1:]) * np.sin(dlon / 2.0) ** 2
    return float(6371.0 * np.sum(2.0 * np.arctan2(np.sqrt(a), np.sqrt(np.maximum(1.0 - a, 0.0)))))


def _chord_length_km(coords: np.ndarray) -> float:
    if coords.shape[0] < 2:
        return 0.0
    return _haversine_length_km(coords[[0, -1]])


def _nearest_grid_values(coords: np.ndarray, lat: np.ndarray, lon: np.ndarray, grid: np.ndarray) -> np.ndarray:
    vals = []
    for lo, la in coords:
        y = int(np.nanargmin(np.abs(lat - la)))
        x = int(np.nanargmin(np.abs(lon - lo)))
        vals.append(grid[y, x])
    return np.asarray(vals, dtype=float)


def _component_to_line(
    ys: np.ndarray,
    xs: np.ndarray,
    z_smooth: np.ndarray,
    lat: np.ndarray,
    lon: np.ndarray,
    score: np.ndarray,
    maps: dict[str, np.ndarray],
    cfg: NmcStyleConfig,
    mode: Mode,
) -> dict | None:
    control, lat0 = _initial_axis_from_component(ys, xs, lat, lon, score, cfg)
    if control.shape[0] < 3:
        return None

    all_xy = _lonlat_to_xy_km(lon[xs], lat[ys], lat0)
    weights = np.maximum(score[ys, xs], 0.05)
    refined = _principal_curve_refine(control, all_xy, weights, cfg)
    final_xy = _smooth_xy_spline(refined, count=cfg.output_points, smooth_factor=cfg.spline_smooth_factor)
    coords = _xy_km_to_lonlat(final_xy, lat0)

    # Drop invalid and duplicate points.
    finite = np.isfinite(coords).all(axis=1)
    coords = coords[finite]
    if coords.shape[0] < 2:
        return None
    coords = _remove_lonlat_close_points(coords, min_step_km=35.0)
    if coords.shape[0] < 2:
        return None

    length_km = _haversine_length_km(coords)
    if length_km < cfg.min_length_km:
        return None
    chord = _chord_length_km(coords)
    sinuosity = length_km / max(chord, 1.0)
    if sinuosity > cfg.max_sinuosity:
        return None

    lons = coords[:, 0]
    lats = coords[:, 1]
    lon_span = float(np.nanmax(lons) - np.nanmin(lons))
    lat_span = float(np.nanmax(lats) - np.nanmin(lats))
    lat_mean = float(np.nanmean(lats))

    # Most of the screenshot artefact near Sri Lanka is a tropical, nearly zonal
    # boundary-following line.  Keep genuine high-latitude horizontal troughs.
    if (
        cfg.reject_tropical_zonal
        and lat_mean < cfg.low_lat_zonal_filter_max_lat
        and lon_span > cfg.low_lat_zonal_max_aspect_ratio * max(lat_span, 0.5)
    ):
        return None

    line_scores = _nearest_grid_values(coords, lat, lon, score)
    line_lap = _nearest_grid_values(coords, lat, lon, maps["lap_score"])
    line_local = _nearest_grid_values(coords, lat, lon, maps["local_score"])
    if np.nanmean(line_scores) < _finite_percentile(score, 55.0):
        return None

    return {
        "coordinates": [[float(lo), float(la)] for lo, la in coords],
        "bbox": [float(np.nanmin(lons)), float(np.nanmin(lats)), float(np.nanmax(lons)), float(np.nanmax(lats))],
        "axis_length_km": float(length_km),
        "sinuosity": float(sinuosity),
        "point_count": int(ys.size),
        "score_mean": float(np.nanmean(line_scores)),
        "score_max": float(np.nanmax(score[ys, xs])),
        "local_score_mean": float(np.nanmean(line_local)),
        "curvature_score_mean": float(np.nanmean(line_lap)),
        "min_z": float(np.nanmin(z_smooth[ys, xs])),
        "max_z": float(np.nanmax(z_smooth[ys, xs])),
        "lat_mean": lat_mean,
        "lon_span": lon_span,
        "lat_span": lat_span,
        "mode": mode,
    }


def _remove_lonlat_close_points(coords: np.ndarray, min_step_km: float) -> np.ndarray:
    if coords.shape[0] <= 1:
        return coords
    keep = [0]
    for i in range(1, coords.shape[0]):
        seg_len = _haversine_length_km(coords[[keep[-1], i]])
        if seg_len >= min_step_km:
            keep.append(i)
    if keep[-1] != coords.shape[0] - 1:
        keep.append(coords.shape[0] - 1)
    return coords[np.asarray(keep, dtype=int)]


def _deduplicate_lines(lines: list[dict]) -> list[dict]:
    """Remove near-duplicate axes using bbox overlap and endpoint distance."""
    kept: list[dict] = []
    for line in lines:
        coords = np.asarray(line["coordinates"], dtype=float)
        duplicate = False
        for old in kept:
            old_coords = np.asarray(old["coordinates"], dtype=float)
            if _polyline_mean_distance_km(coords, old_coords) < 220.0:
                duplicate = True
                if line["score_mean"] > old["score_mean"]:
                    kept.remove(old)
                    kept.append(line)
                break
        if not duplicate:
            kept.append(line)
    return kept


def _polyline_mean_distance_km(a: np.ndarray, b: np.ndarray) -> float:
    if a.shape[0] == 0 or b.shape[0] == 0:
        return float("inf")
    # simple lon/lat to local xy for speed
    lat0 = float(np.nanmedian(np.concatenate([a[:, 1], b[:, 1]])))
    ax = _lonlat_to_xy_km(a[:, 0], a[:, 1], lat0)
    bx = _lonlat_to_xy_km(b[:, 0], b[:, 1], lat0)
    d2 = ((ax[:, None, :] - bx[None, :, :]) ** 2).sum(axis=2)
    return float(np.nanmean(np.sqrt(np.nanmin(d2, axis=1))))


def _zonal_valley_tracks(
    z500: np.ndarray,
    lat: np.ndarray,
    lon: np.ndarray,
    cfg: NmcStyleConfig,
) -> list[list[tuple[int, int, float]]]:
    """Track persistent zonal height minima from south to north.

    This complements the two-dimensional percentile components.  It is aimed at
    sparse sounding analyses where a shallow trough is coherent over latitude
    but too weak to exceed a single full-domain score threshold.
    """
    _, dx_km = _grid_spacing_km(lat, lon)
    radius = max(2, int(round(cfg.meridional_track_window_km / max(dx_km, 1.0))))
    track_field = _nan_gaussian(z500, (0.45, 0.45))
    row_candidates: list[list[tuple[int, float]]] = []

    for y, latitude in enumerate(lat):
        candidates: list[tuple[int, float]] = []
        if cfg.meridional_track_lat_min <= latitude <= cfg.meridional_track_lat_max:
            for x in range(radius, lon.size - radius):
                if not cfg.meridional_track_lon_min <= lon[x] <= cfg.meridional_track_lon_max:
                    continue
                values = track_field[y, [x - radius, x - 1, x, x + 1, x + radius]]
                if not np.isfinite(values).all():
                    continue
                if not (track_field[y, x] <= track_field[y, x - 1] and track_field[y, x] < track_field[y, x + 1]):
                    continue
                depth = min(
                    float(track_field[y, x - radius] - track_field[y, x]),
                    float(track_field[y, x + radius] - track_field[y, x]),
                )
                if depth >= cfg.meridional_track_min_depth_gpm:
                    candidates.append((x, depth))
        row_candidates.append(candidates)

    tracks: list[list[tuple[int, int, float]]] = []
    for y, candidates in enumerate(row_candidates):
        pairs: list[tuple[float, int, int]] = []
        for track_index, track in enumerate(tracks):
            last_y, last_x, _ = track[-1]
            row_gap = y - last_y
            if not 1 <= row_gap <= cfg.meridional_track_max_gap_rows + 1:
                continue
            for candidate_index, (x, depth) in enumerate(candidates):
                lon_step = abs(float(lon[x] - lon[last_x]))
                if lon_step <= cfg.meridional_track_max_lon_step_deg * row_gap:
                    pairs.append((lon_step - 0.08 * min(depth, 10.0), track_index, candidate_index))

        used_tracks: set[int] = set()
        used_candidates: set[int] = set()
        for _, track_index, candidate_index in sorted(pairs):
            if track_index in used_tracks or candidate_index in used_candidates:
                continue
            x, depth = candidates[candidate_index]
            tracks[track_index].append((y, x, depth))
            used_tracks.add(track_index)
            used_candidates.add(candidate_index)
        for candidate_index, (x, depth) in enumerate(candidates):
            if candidate_index not in used_candidates:
                tracks.append([(y, x, depth)])

    accepted: list[list[tuple[int, int, float]]] = []
    for track in tracks:
        ys = np.asarray([item[0] for item in track], dtype=int)
        depths = np.asarray([item[2] for item in track], dtype=float)
        if len(track) < cfg.meridional_track_min_points:
            continue
        if float(np.ptp(lat[ys])) < cfg.meridional_track_min_lat_span_deg:
            continue
        if float(np.nanmean(depths)) < cfg.meridional_track_min_mean_depth_gpm:
            continue
        if float(np.nanmax(depths)) < cfg.meridional_track_min_peak_depth_gpm:
            continue
        accepted.append(track)

    accepted.sort(
        key=lambda track: (
            float(np.ptp(lat[np.asarray([item[0] for item in track], dtype=int)]))
            * float(np.nanmean([item[2] for item in track])),
            len(track),
        ),
        reverse=True,
    )
    return accepted


def _valley_track_to_line(
    track: list[tuple[int, int, float]],
    z500: np.ndarray,
    lat: np.ndarray,
    lon: np.ndarray,
    score: np.ndarray,
    maps: dict[str, np.ndarray],
    cfg: NmcStyleConfig,
) -> dict | None:
    ys = np.asarray([item[0] for item in track], dtype=int)
    xs = np.asarray([item[1] for item in track], dtype=int)
    depths = np.asarray([item[2] for item in track], dtype=float)
    source_coords = np.column_stack([lon[xs], lat[ys]]).astype(float)
    lat0 = float(np.nanmedian(source_coords[:, 1]))
    source_xy = _lonlat_to_xy_km(source_coords[:, 0], source_coords[:, 1], lat0)
    output_count = max(12, min(cfg.output_points, source_coords.shape[0] * 2))
    final_xy = _smooth_xy_spline(source_xy, count=output_count, smooth_factor=0.8)
    coords = _xy_km_to_lonlat(final_xy, lat0)
    coords[:, 0] = np.clip(coords[:, 0], float(np.nanmin(source_coords[:, 0])), float(np.nanmax(source_coords[:, 0])))
    coords[:, 1] = np.clip(coords[:, 1], float(np.nanmin(source_coords[:, 1])), float(np.nanmax(source_coords[:, 1])))
    coords = _remove_lonlat_close_points(coords, min_step_km=35.0)
    if coords.shape[0] < 2:
        return None

    length_km = _haversine_length_km(coords)
    if length_km < cfg.min_length_km:
        return None
    chord = _chord_length_km(coords)
    sinuosity = length_km / max(chord, 1.0)
    if sinuosity > cfg.max_sinuosity:
        return None

    lons = coords[:, 0]
    lats = coords[:, 1]
    line_scores = _nearest_grid_values(coords, lat, lon, score)
    line_lap = _nearest_grid_values(coords, lat, lon, maps["lap_score"])
    line_local = _nearest_grid_values(coords, lat, lon, maps["local_score"])
    return {
        "coordinates": [[float(lo), float(la)] for lo, la in coords],
        "bbox": [float(np.nanmin(lons)), float(np.nanmin(lats)), float(np.nanmax(lons)), float(np.nanmax(lats))],
        "axis_length_km": float(length_km),
        "sinuosity": float(sinuosity),
        "point_count": int(len(track)),
        "score_mean": float(np.nanmean(line_scores)),
        "score_max": float(np.nanmax(line_scores)),
        "local_score_mean": float(np.nanmean(line_local)),
        "curvature_score_mean": float(np.nanmean(line_lap)),
        "min_z": float(np.nanmin(z500[ys, xs])),
        "max_z": float(np.nanmax(z500[ys, xs])),
        "lat_mean": float(np.nanmean(lats)),
        "lon_span": float(np.ptp(lons)),
        "lat_span": float(np.ptp(lats)),
        "mode": "trough",
        "candidate_source": "meridional_valley_track",
        "valley_depth_mean_gpm": float(np.nanmean(depths)),
        "valley_depth_max_gpm": float(np.nanmax(depths)),
    }


def _line_coverage_near_existing(line: dict, existing: list[dict], distance_km: float) -> float:
    if not existing:
        return 0.0
    coords = np.asarray(line["coordinates"], dtype=float)
    reference = np.vstack([np.asarray(item["coordinates"], dtype=float) for item in existing])
    lat0 = float(np.nanmedian(np.concatenate([coords[:, 1], reference[:, 1]])))
    xy = _lonlat_to_xy_km(coords[:, 0], coords[:, 1], lat0)
    reference_xy = _lonlat_to_xy_km(reference[:, 0], reference[:, 1], lat0)
    distances = np.sqrt(np.min(((xy[:, None, :] - reference_xy[None, :, :]) ** 2).sum(axis=2), axis=1))
    return float(np.mean(distances <= distance_km))


def _detect_axis_features(
    z500: np.ndarray,
    lat: np.ndarray,
    lon: np.ndarray,
    cfg: NmcStyleConfig,
    mode: Mode,
    vorticity: np.ndarray | None,
) -> list[dict]:
    dy_km, dx_km = _grid_spacing_km(lat, lon)
    sigma_y = max(cfg.min_sigma_grid, cfg.smooth_radius_km / max(dy_km, 1.0))
    sigma_x = max(cfg.min_sigma_grid, cfg.smooth_radius_km / max(dx_km, 1.0))
    z_large = _nan_gaussian(z500, (sigma_y, sigma_x))

    # Use a second, lighter smoothing on the final score map.  This stabilizes
    # candidate regions but still lets the axis sit near the real height trough.
    score, maps = _build_score(z_large, lat, lon, cfg, mode, vorticity)
    s2_y = max(0.0, cfg.second_smooth_radius_km / max(dy_km, 1.0))
    s2_x = max(0.0, cfg.second_smooth_radius_km / max(dx_km, 1.0))
    score_smooth = _nan_gaussian(score, (s2_y, s2_x)) if cfg.second_smooth_radius_km > 0 else score
    maps = {**maps, "score": score_smooth}

    valid_mask = _domain_mask(lat, lon, cfg) & np.isfinite(z_large)
    components = _candidate_components(score_smooth, maps, valid_mask, cfg)

    lines: list[dict] = []
    for ys, xs in components:
        line = _component_to_line(ys, xs, z_large, lat, lon, score_smooth, maps, cfg, mode)
        if line is not None:
            lines.append(line)

    # Sort by a blend of strength and length, not length alone.  The previous
    # version sorted by length/point_count, which favours long boundary artefacts.
    lines.sort(
        key=lambda item: (
            item["score_mean"] * 1.8 + item["score_max"] * 0.8,
            min(item["axis_length_km"], 2500.0) / 2500.0,
            item["point_count"],
        ),
        reverse=True,
    )
    lines = _deduplicate_lines(lines)
    if mode != "trough" or not cfg.enable_meridional_valley_tracks:
        return lines[: cfg.max_lines]

    supplemental: list[dict] = []
    for track in _zonal_valley_tracks(z500, lat, lon, cfg):
        line = _valley_track_to_line(track, z500, lat, lon, score_smooth, maps, cfg)
        if line is None:
            continue
        coverage = _line_coverage_near_existing(line, lines, cfg.meridional_track_overlap_distance_km)
        if coverage > cfg.meridional_track_max_existing_coverage:
            continue
        line["existing_line_coverage"] = coverage
        supplemental.append(line)
        if len(supplemental) >= cfg.meridional_track_max_lines:
            break

    primary_limit = max(0, cfg.max_lines - len(supplemental))
    return [*lines[:primary_limit], *supplemental]


def _feature_from_line(line: dict, rank: int, mode: Mode, cfg: NmcStyleConfig) -> dict:
    feature_type = "trough" if mode == "trough" else "ridge"
    title = "500hPa 槽线" if mode == "trough" else "500hPa 脊线"
    confidence = min(0.92, cfg.base_confidence + 0.08 * min(line["score_mean"], 1.0))
    return line_feature(
        line["coordinates"],
        {
            "id": f"{feature_type}_{rank:03d}",
            "feature_type": feature_type,
            "title": title,
            "level": "500hPa",
            "confidence": float(confidence),
            "method": "nmc_style_synoptic_axis_v7",
            "analysis_domain": {
                "lon_min": float(cfg.analysis_lon_min),
                "lon_max": float(cfg.analysis_lon_max),
                "lat_min": float(cfg.analysis_lat_min),
                "lat_max": float(cfg.analysis_lat_max),
            },
            "axis_length_km": float(line["axis_length_km"]),
            "sinuosity": float(line["sinuosity"]),
            "point_count": int(line["point_count"]),
            "score_mean": float(line["score_mean"]),
            "score_max": float(line["score_max"]),
            "local_score_mean": float(line["local_score_mean"]),
            "curvature_score_mean": float(line["curvature_score_mean"]),
            "min_z500_gpm": float(line["min_z"]),
            "max_z500_gpm": float(line["max_z"]),
            "candidate_source": line.get("candidate_source", "synoptic_score_component"),
            "valley_depth_mean_gpm": line.get("valley_depth_mean_gpm"),
            "valley_depth_max_gpm": line.get("valley_depth_max_gpm"),
            "evidence": [
                "500hPa 位势高度场经过天气尺度平滑",
                "轴线由局地槽脊极值、拉普拉斯曲率、等高线弯曲、纬向距平综合评分确定",
                "候选区域按强评分种子约束，轴线用主曲线/样条平滑生成",
                "候选提取和排序仅在配置的经纬度业务范围内进行",
                "稀疏实况场中的弱槽可由逐纬度局地低谷连续跟踪补充",
                "过滤热带近东西向边界伪线和过短、过弯折线段",
            ],
        },
    )


# ---------------------------------------------------------------------------
# Backward-compatible candidate API
# ---------------------------------------------------------------------------
def _trough_ridge_axis_candidate_records(
    anom: np.ndarray,
    lat,
    lon,
    *,
    mode: str,
    percentile: float,
    min_points: int,
    max_lines: int,
    curvature_percentile: float = 55.0,
    smoothing_sigma: float = 1.0,
    vorticity: np.ndarray | None = None,
) -> list[dict]:
    """Return NMC-style trough/ridge axis candidates.

    This keeps the public helper name and calling convention used by the
    earlier Codex implementation, but the internals use the smoother
    synoptic-scale axis construction from this module.

    Parameters
    ----------
    anom:
        2-D input field.  For backward compatibility this is usually the
        500 hPa zonal anomaly, but the function also works with a height field.
    lat, lon:
        1-D coordinate arrays.
    mode:
        ``"trough"`` or ``"ridge"``.
    percentile:
        Tail percentile of ``anom`` used as a broad candidate gate.  For troughs
        ``20`` means values below P20; for ridges it means values above P80.
    min_points:
        Minimum number of connected grid points in a candidate component.
    max_lines:
        Maximum number of candidates to return.
    curvature_percentile:
        Percentile gate for signed Laplacian/curvature support.
    smoothing_sigma:
        Grid-space Gaussian smoothing sigma used by the compatibility helper.
    vorticity:
        Optional relative vorticity. Positive values support troughs; negative
        values support ridges.

    Returns
    -------
    list[dict]
        Raw candidate dictionaries.  They include only line coordinates and
        scalar metadata; no ``bbox``/extent/mask/polygon geometry is returned, so
        the object cannot be mistaken for a filled area by Web GIS code.
    """
    if mode not in {"trough", "ridge"}:
        raise ValueError("mode must be trough or ridge")
    axis_mode: Mode = "trough" if mode == "trough" else "ridge"

    field, lat_arr, lon_arr, vort = _prepare_lat_lon_field(
        np.asarray(anom, dtype=float), lat, lon, vorticity
    )

    # Keep the old helper's grid-sigma behaviour instead of forcing the full
    # physical-radius smoothing used by detect_trough_ridge().  This makes the
    # helper a safer drop-in replacement for existing calls.
    sigma = max(0.0, float(smoothing_sigma))
    smooth = _nan_gaussian(field, (sigma, sigma)) if sigma > 0 else field.copy()

    cfg = NmcStyleConfig(
        min_sigma_grid=max(0.0, sigma),
        min_points_per_line=max(1, int(min_points)),
        max_lines=max(1, int(max_lines)),
        # Candidate helper should expose candidates, not aggressively remove
        # short systems.  Final filtering is still available in detect_trough_ridge.
        min_length_km=0.0,
        component_percentile=70.0,
        seed_percentile=82.0,
        local_extreme_min_score=0.05,
        curvature_min_score=0.02,
        # Use a gentler line style for raw candidates while keeping the line
        # much smoother than the original grid-snapped candidate axis.
        axis_control_spacing_km=220.0,
        output_points=32,
        spline_smooth_factor=2.2,
        reject_tropical_zonal=False,
    )

    score, maps = _build_score(smooth, lat_arr, lon_arr, cfg, axis_mode, vort)
    valid_mask = _domain_mask(lat_arr, lon_arr, cfg) & np.isfinite(smooth)

    # Backward-compatible broad tail mask.  The old implementation used P20 for
    # troughs and P80 for ridges when percentile=20.
    p = float(np.clip(percentile, 0.0, 100.0))
    tail_q = p if axis_mode == "trough" else 100.0 - p
    threshold_value = _finite_percentile(smooth[valid_mask], tail_q)
    tail_mask = smooth <= threshold_value if axis_mode == "trough" else smooth >= threshold_value

    lap_support = maps["laplacian"] if axis_mode == "trough" else -maps["laplacian"]
    curvature_support = np.maximum(lap_support, 0.0) + 0.25 * np.abs(maps["contour_curvature"])
    curvature_threshold = max(
        0.0,
        _finite_percentile(curvature_support[valid_mask], float(curvature_percentile)),
    )

    domain_score = score[valid_mask & tail_mask & np.isfinite(score)]
    if domain_score.size:
        score_threshold = float(np.nanpercentile(domain_score, max(50.0, min(92.0, 100.0 - p))))
    else:
        score_threshold = _finite_percentile(score[valid_mask], 75.0)

    base = (
        valid_mask
        & tail_mask
        & (score >= score_threshold)
        & (curvature_support >= curvature_threshold)
        & (maps["local_score"] >= cfg.local_extreme_min_score)
    )

    structure = np.ones((3, 3), dtype=bool)
    base = ndimage.binary_opening(base, structure=structure, iterations=1)
    base = ndimage.binary_dilation(base, structure=structure, iterations=1) & valid_mask & tail_mask

    labels, count = ndimage.label(base, structure=structure.astype(int))
    components: list[tuple[np.ndarray, np.ndarray]] = []
    for label_id in range(1, count + 1):
        ys, xs = np.where(labels == label_id)
        if ys.size >= cfg.min_points_per_line:
            components.append((ys, xs))

    # If the signed curvature gate is too strict, fall back to the score-gated
    # tail mask.  This mirrors the old function's anomaly_component_axis fallback
    # while still using the smoother line constructor.
    method = "curvature_component_axis"
    method_detail = "nmc_style_curvature_candidate_axis"
    if not components:
        method = "anomaly_component_axis"
        method_detail = "nmc_style_score_candidate_axis"
        fallback = valid_mask & tail_mask & (score >= _finite_percentile(score[valid_mask & tail_mask], 65.0))
        labels, count = ndimage.label(fallback, structure=structure.astype(int))
        for label_id in range(1, count + 1):
            ys, xs = np.where(labels == label_id)
            if ys.size >= cfg.min_points_per_line:
                components.append((ys, xs))

    candidates: list[dict] = []
    vort_support = None
    if vort is not None:
        vort_support = vort if axis_mode == "trough" else -vort

    for ys, xs in components:
        line = _component_to_line(ys, xs, smooth, lat_arr, lon_arr, score, maps, cfg, axis_mode)
        if line is None:
            continue
        values = field[ys, xs]
        curvature_values = curvature_support[ys, xs]
        vort_mean = None
        if vort_support is not None:
            support_values = vort_support[ys, xs]
            if np.isfinite(support_values).any():
                vort_mean = float(np.nanmean(support_values))
        axis_length_km = float(line["axis_length_km"])
        line_coords = np.asarray(line["coordinates"], dtype=float)
        axis_length_degree = float(
            np.sum(
                np.hypot(
                    np.diff(line_coords[:, 0]),
                    np.diff(line_coords[:, 1]),
                )
            )
        ) if line_coords.shape[0] >= 2 else 0.0
        candidates.append(
            {
                "rank": 0,
                "mode": axis_mode,
                "method": method,
                "method_detail": method_detail,
                "coordinates": line["coordinates"],
                    "point_count": int(ys.size),
                    #"bbox": [],
                # Preserve the old Codex field semantics: axis_length is the
                # simple lon/lat polyline length.  New code should prefer the
                # explicit geodesic value axis_length_km.
                "axis_length": axis_length_degree,
                "axis_length_km": axis_length_km,
                "sinuosity": float(line["sinuosity"]),
                "score_mean": float(line["score_mean"]),
                "score_max": float(line["score_max"]),
                "threshold_value": float(threshold_value),
                "curvature_threshold": float(curvature_threshold),
                "curvature_mean": float(np.nanmean(curvature_values)),
                "vorticity_support_mean": vort_mean,
                "min_value": float(np.nanmin(values)),
                "max_value": float(np.nanmax(values)),
                "mean_value": float(np.nanmean(values)),
            }
        )

    # 候选槽/脊线用于业务出图时，应优先保留天气尺度的连续轴线，
    # 不能让紧凑但很深的小低涡因局地 score 高而排到主槽前面。
    candidates.sort(
        key=lambda item: (
            min(float(item["axis_length_km"]), 3000.0) / 3000.0,
            int(item["point_count"]),
            float(item["score_mean"]) * 1.2 + float(item["score_max"]) * 0.4,
        ),
        reverse=True,
    )
    for rank, candidate in enumerate(candidates[: max(1, int(max_lines))], start=1):
        candidate["rank"] = rank
    return candidates[: max(1, int(max_lines))]




def _candidate_record_to_feature(candidate: dict, *, feature_type: str | None = None) -> dict:
    """Convert one raw candidate record into a strict GeoJSON LineString feature.

    The returned object is a valid GeoJSON Feature, but it also carries the old
    scalar fields at the top level as foreign members.  That keeps old endpoint
    code such as ``candidate["threshold_value"]`` from failing when a caller asks
    for GeoJSON output.  Area-like members such as bbox/extent/mask are still
    deliberately omitted.
    """
    mode = str(candidate.get("mode", "trough"))
    feature_type = feature_type or ("trough_candidate" if mode == "trough" else "ridge_candidate")
    title = "500hPa 槽线候选" if mode == "trough" else "500hPa 脊线候选"
    props = {
        "id": f"{feature_type}_{int(candidate.get('rank', 0)):03d}",
        "feature_type": feature_type,
        "candidate_type": "axis_line",
        "title": title,
        "level": "500hPa",
        "rank": int(candidate.get("rank", 0)),
        "mode": mode,
        "method": candidate.get("method"),
        "confidence": 0.70 if "curvature" in str(candidate.get("method", "")) else 0.60,
        "point_count": int(candidate.get("point_count", 0)),
        "axis_length": float(candidate.get("axis_length", 0.0)),
        "axis_length_km": float(candidate.get("axis_length_km", 0.0)),
        "sinuosity": float(candidate.get("sinuosity", 0.0)),
        "score_mean": float(candidate.get("score_mean", 0.0)),
        "score_max": float(candidate.get("score_max", 0.0)),
        "threshold_value": float(candidate.get("threshold_value", np.nan)),
        "curvature_threshold": float(candidate.get("curvature_threshold", np.nan)),
        "curvature_mean": float(candidate.get("curvature_mean", np.nan)),
        "vorticity_support_mean": candidate.get("vorticity_support_mean"),
        "min_value": float(candidate.get("min_value", np.nan)),
        "max_value": float(candidate.get("max_value", np.nan)),
        "mean_value": float(candidate.get("mean_value", np.nan)),
        "evidence": [
            "500hPa 位势高度距平达到尾部分位",
            "候选轴线由综合评分区提取后用主曲线/样条平滑生成",
            "输出为严格 GeoJSON LineString，不携带候选面区域",
        ],
    }
    if props["vorticity_support_mean"] is not None:
        props["evidence"].append("500hPa 相对涡度符号与槽脊性质一致")

    feature = _strict_line_feature(candidate.get("coordinates", []), props)

    # Backward-compatible foreign members.  Some existing service code still
    # reads candidate["threshold_value"], candidate["coordinates"], etc. from
    # the object returned by trough_ridge_axis_candidates().  Keep these scalar
    # fields available without reintroducing bbox/polygon/mask data.
    for key in (
        "rank",
        "mode",
        "method",
        "coordinates",
        "point_count",
        "axis_length",
        "axis_length_km",
        "sinuosity",
        "score_mean",
        "score_max",
        "threshold_value",
        "curvature_threshold",
        "curvature_mean",
        "vorticity_support_mean",
        "min_value",
        "max_value",
        "mean_value",
    ):
        if key in candidate:
            feature[key] = candidate[key]
    return feature


def trough_ridge_axis_candidate_records(
    anom: np.ndarray,
    lat,
    lon,
    *,
    mode: str,
    percentile: float,
    min_points: int,
    max_lines: int,
    curvature_percentile: float = 55.0,
    smoothing_sigma: float = 1.0,
    vorticity: np.ndarray | None = None,
) -> list[dict]:
    """Return raw line candidate records with no area/bbox geometry."""
    return _trough_ridge_axis_candidate_records(
        anom,
        lat,
        lon,
        mode=mode,
        percentile=percentile,
        min_points=min_points,
        max_lines=max_lines,
        curvature_percentile=curvature_percentile,
        smoothing_sigma=smoothing_sigma,
        vorticity=vorticity,
    )


def trough_ridge_axis_candidate_features(
    anom: np.ndarray,
    lat,
    lon,
    *,
    mode: str,
    percentile: float,
    min_points: int,
    max_lines: int,
    curvature_percentile: float = 55.0,
    smoothing_sigma: float = 1.0,
    vorticity: np.ndarray | None = None,
) -> list[dict]:
    """Return trough/ridge candidates as strict GeoJSON LineString features."""
    records = trough_ridge_axis_candidate_records(
        anom,
        lat,
        lon,
        mode=mode,
        percentile=percentile,
        min_points=min_points,
        max_lines=max_lines,
        curvature_percentile=curvature_percentile,
        smoothing_sigma=smoothing_sigma,
        vorticity=vorticity,
    )
    return [_candidate_record_to_feature(record) for record in records]


def trough_ridge_axis_candidates(
    anom: np.ndarray,
    lat,
    lon,
    *,
    mode: str,
    percentile: float,
    min_points: int,
    max_lines: int,
    curvature_percentile: float = 55.0,
    smoothing_sigma: float = 1.0,
    vorticity: np.ndarray | None = None,
    return_geojson: bool = False,
) -> list[dict]:
    """Return trough/ridge candidate axes.

    Compatibility note
    ------------------
    The original Codex helper returned raw candidate dictionaries with top-level
    fields such as ``coordinates`` and ``threshold_value``.  v4 changed the
    default to GeoJSON Feature and some existing endpoint code then raised
    ``KeyError: 'threshold_value'``.  v5 restores the old default: raw records
    are returned unless ``return_geojson=True`` is passed.

    Both modes are line-only.  The raw records no longer include ``bbox``,
    ``extent``, ``mask`` or polygon-like members, so they will not create filled
    rectangles/areas when converted correctly to a line layer.
    """
    records = trough_ridge_axis_candidate_records(
        anom,
        lat,
        lon,
        mode=mode,
        percentile=percentile,
        min_points=min_points,
        max_lines=max_lines,
        curvature_percentile=curvature_percentile,
        smoothing_sigma=smoothing_sigma,
        vorticity=vorticity,
    )
    if return_geojson:
        return [_candidate_record_to_feature(record) for record in records]
    return records


def _candidate_lines_from_anomaly(
    anom: np.ndarray,
    lat,
    lon,
    *,
    mode: str,
    percentile: float,
    min_points: int,
    max_lines: int,
    curvature_percentile: float,
    smoothing_sigma: float,
    vorticity: np.ndarray | None = None,
) -> list[dict]:
    """Compatibility wrapper returning GeoJSON features from candidates."""
    features = []
    for candidate in trough_ridge_axis_candidate_records(
        anom,
        lat,
        lon,
        mode=mode,
        percentile=percentile,
        min_points=min_points,
        max_lines=max_lines,
        curvature_percentile=curvature_percentile,
        smoothing_sigma=smoothing_sigma,
        vorticity=vorticity,
    ):
        feature_type = "trough" if mode == "trough" else "ridge"
        title = "500hPa 槽线" if mode == "trough" else "500hPa 脊线"
        evidence = [
            "500hPa 位势高度距平达到尾部分位",
            "轴线由 NMC-style 综合评分候选区和主曲线/样条平滑生成",
        ]
        if candidate["vorticity_support_mean"] is not None:
            evidence.append("500hPa 相对涡度符号与槽脊性质一致")
        features.append(
            _strict_line_feature(
                candidate["coordinates"],
                {
                    "id": f"{feature_type}_{candidate['rank']:03d}",
                    "feature_type": feature_type,
                    "title": title,
                    "level": "500hPa",
                    "confidence": 0.70 if "curvature" in str(candidate.get("method_detail") or candidate.get("method") or "") else 0.60,
                    "method": candidate["method"],
                    "point_count": candidate["point_count"],
                    "axis_length": candidate["axis_length"],
                    "axis_length_km": candidate["axis_length_km"],
                    "sinuosity": candidate["sinuosity"],
                    "score_mean": candidate["score_mean"],
                    "threshold_value": candidate["threshold_value"],
                    "curvature_mean": candidate["curvature_mean"],
                    "vorticity_support_mean": candidate["vorticity_support_mean"],
                    "evidence": evidence,
                },
            )
        )
    return features


def detect_trough_ridge(
    z500: np.ndarray,
    lat,
    lon,
    thresholds: dict | None = None,
    vorticity500: np.ndarray | None = None,
) -> tuple[list[dict], list[dict]]:
    """Detect NMC-style smooth 500 hPa trough/ridge axes.

    The function keeps the old public signature.  By default it returns troughs
    and ridges.  To disable ridge detection, pass:

        thresholds = {"trough_ridge": {"detect_ridge": False}}
    """
    z = _maybe_geopotential_to_height(np.asarray(z500, dtype=float))
    z, lat_arr, lon_arr, vort = _prepare_lat_lon_field(z, lat, lon, vorticity500)
    cfg = _cfg_from_thresholds(thresholds)
    raw_cfg = (thresholds or {}).get("trough_ridge", thresholds or {})
    detect_ridge = bool(raw_cfg.get("detect_ridge", True))

    trough_lines = _detect_axis_features(z, lat_arr, lon_arr, cfg, "trough", vort)
    troughs = [_feature_from_line(line, rank, "trough", cfg) for rank, line in enumerate(trough_lines, start=1)]

    ridges: list[dict] = []
    if detect_ridge:
        ridge_lines = _detect_axis_features(z, lat_arr, lon_arr, cfg, "ridge", vort)
        ridges = [_feature_from_line(line, rank, "ridge", cfg) for rank, line in enumerate(ridge_lines, start=1)]
    return troughs, ridges


# Optional direct helper if only troughs are needed.
def detect_z500_troughs_nmc_style(
    z500: np.ndarray,
    lat,
    lon,
    thresholds: dict | None = None,
    vorticity500: np.ndarray | None = None,
) -> list[dict]:
    troughs, _ = detect_trough_ridge(
        z500,
        lat,
        lon,
        {**(thresholds or {}), "trough_ridge": {**((thresholds or {}).get("trough_ridge", {})), "detect_ridge": False}},
        vorticity500=vorticity500,
    )
    return troughs
